---
apiVersion: v1
kind: Service
metadata:
    name: nginx
spec:
  type: NodePort
  selector:
    app: nginx
  ports:
  - targetPort: 80
    nodePort: 30001
    port: 8080
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx
spec:
  selector:
    matchLabels:
      app: nginx
  template:
    metadata:
      labels:
        app: nginx
    spec:
      affinity:
        podAntiAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            - labelSelector:
                matchExpressions:
                - key: app
                  operator: In
                  values:
                    - nginx
              topologyKey: "kubernetes.io/hostname"
      containers:
        - name: nginx
          image: nginx
          ports:
            - containerPort: 80
              hostPort: 7080
          image: ec2-13-48-203-54.eu-north-1.compute.amazonaws.com:30000/nginx
