- hosts: all
  gather_facts: no
  tasks:
    - synchronize:
        src: /ansible/control
        dest: ~/
        recursive: yes
        delete: yes
        mode: push
- hosts: master
  gather_facts: no
  tasks:
    - copy:
        src: /.aws/id_rsa_worker
        dest: ~/.ssh/id_rsa
    - file:
        path: ~/.ssh/id_rsa
        mode: '400'
    - shell:
        cmd: |
          cat > ~/.ssh/config <<EOF
          Host worker
            User ubuntu
            HostName {{ private_worker_ip }}
            IdentityFile ~/.ssh/id_rsa
            StrictHostKeyChecking no
          EOF
