- hosts: all
  gather_facts: yes
  tasks:
    - synchronize:
        src: /ansible/control
        dest: ~/
        recursive: yes
        delete: yes
        mode: push
- hosts: master
  gather_facts: no
  tasks:
    - copy:
        src: /.aws/id_rsa_worker
        dest: ~/.ssh/id_rsa
    - file:
        path: ~/.ssh/id_rsa
        mode: '400'
    - name: .ssh/config
      shell:
        cmd: |
          cat > ~/.ssh/config <<EOF
          Host worker
            User ubuntu
            HostName {{ hostvars['worker']['ansible_default_ipv4']['address'] }}
            IdentityFile ~/.ssh/id_rsa
            StrictHostKeyChecking no
          EOF
