- hosts: control
  tasks:
    - synchronize:
        src: /ansible/control
        dest: ~/
        recursive: yes
        delete: yes
        mode: push
    - copy:
        src: /terraform/ip_worker.txt
        dest: ~/ip_worker.txt
    