- hosts: all
  gather_facts: no
  become: yes
  tasks:
    - shell: |
        until ssh -i {{ansible_ssh_private_key_file}} -o StrictHostKeyChecking=no -o ConnectTimeout=5 {{ansible_user}}@{{ansible_host}} -p {{ansible_port|default(22)}} echo ok 2>&1;
        do
          :;
        done
      delegate_to: localhost
    - name: install python
      raw: apt update && apt install -y python
    - name: install ansible
      apt:
        pkg:
          - ansible
          - bridge-utils
          - cgroup-tools
          - bpfcc-tools
          - unzip
          - socat
          - tree
          - jq
    - lineinfile:
        line: echo -e "\\033]1337;SetProfile=Prod\\a"
        path: /home/ubuntu/.bashrc
    - lineinfile:
        line: echo -e "\\033]1337;SetProfile=Default\\a"
        path: /home/ubuntu/.bash_logout
    - command: fallocate -l 3G /swapfile
    - command: chmod 600 /swapfile
    - command: mkswap /swapfile
    - command: swapon /swapfile
    - command: sysctl vm.swappiness=25
