- hosts: all
  gather_facts: no
  become: yes
  tasks:
    - name: install python
      raw: apt update && apt install -y python
    - name: install ansible
      apt:
        pkg:
          - ansible
          - bridge-utils
          - unzip
          - socat
          - tree
          - jq
