- hosts: control
  gather_facts: no
  become: yes
  tasks:
    - name: install python
      raw: apt-get update && apt-get install -y python
- hosts: control
  tasks:
    - name: ping
      ping:
    - name: copy
      synchronize:
        src: ../control
        dest: ~/
        recursive: yes
        delete: yes
        mode: push