- hosts: all
  gather_facts: no
  become: yes
  tasks:
    - name: kubeadm reset
      command: kubeadm reset -f
- hosts: master
  gather_facts: no
  become: yes
  tasks:
    - name: delete /etc/cni/net.d
      file:
        path: /etc/cni/net.d
        state: absent
    - name: delete helm
      file:
        path: /usr/local/bin/helm
        state: absent
    - name: stop kubelet
      systemd:
        name: kubelet
        state: stopped
        enabled: no
