- hosts: master
  gather_facts: no
  tasks:
    - name: delete kubernetes dir
      file:
        path: ~/kubernetes
        state: absent
    - name: clone kubernetes
      git:
        repo: https://github.com/kubernetes/kubernetes
        depth: 1
        dest: ~/kubernetes
    - name: delete test files
      shell: find kubernetes -name '*test*' -exec rm -rf {} \;
    - name: delete non-Golang files
      shell: find kubernetes -not -name '*.go' -and -type f -delete
