- hosts: master
  gather_facts: no
  tasks:
    - file:
        path: ~/kubernetes
        state: absent
    - git:
        repo: https://github.com/kubernetes/kubernetes
        depth: 1
        dest: ~/kubernetes
    - shell: find kubernetes -name '*_test.go' -type f -delete
    - shell: find kubernetes -not -name '*.go' -and -type f -delete
