- hosts: master
  gather_facts: no
  become: yes
  tasks:
    - shell:
        cmd: |
          HELM_VERSION="v3.0.2"
          mkdir -p /opt/helm && cd /opt/helm
          curl -sO "https://get.helm.sh/helm-${HELM_VERSION}-linux-amd64.tar.gz"
          curl -sO "https://get.helm.sh/helm-${HELM_VERSION}-linux-amd64.tar.gz.sha256"
          sha256sum helm-${HELM_VERSION}-linux-amd64.tar.gz && cat helm-${HELM_VERSION}-linux-amd64.tar.gz.sha256
          tar -zxvf helm-${HELM_VERSION}-linux-amd64.tar.gz
    - command: ln /opt/helm/linux-amd64/helm /usr/local/bin/helm
    - command: helm repo add stable https://kubernetes-charts.storage.googleapis.com/
# - hosts: master
#   gather_facts: no
#   tasks:
#     - command: helm install stable/redis --generate-name
