- hosts: all
  become: yes
  gather_facts: no
  tasks:
    - name: create /etc/containerd
      file:
        path: /etc/containerd/
        state: directory
        owner: ubuntu
        group: ubuntu
    - name: create /etc/containerd/config.toml
      shell:
        cmd: |
          cat > /etc/containerd/config.toml <<EOF
          [debug]
            level = "trace"
          EOF
    - name: install containerd
      apt:
        pkg: containerd
    - name: restart containerd
      systemd:
        name: containerd
        daemon_reload: yes
        state: restarted
        enabled: yes
    - name: install crictl
      shell:
        cmd: |
          CRICTL_VERSION="v1.16.0"
          curl -L "https://github.com/kubernetes-sigs/cri-tools/releases/download/${CRICTL_VERSION}/crictl-${CRICTL_VERSION}-linux-amd64.tar.gz" | tar -C /usr/local/bin -xz
