- hosts: all
  become: yes
  gather_facts: no
  vars:
    CRICTL_VERSION: v1.16.0
  tasks:
    - file:
        path: /etc/containerd
        state: directory
    - copy: 
        dest: /etc/containerd/config.toml
        content: |
          #[debug]
          #  level = "trace"
    - file:
        path: /etc/systemd/system/containerd.service.d
        state: directory
    - copy:
        dest: /etc/systemd/system/containerd.service.d/override.conf
        content: |
          [Service]
          #Environment="GODEBUG=http2debug=1"
    - apt:
        pkg: containerd
    - shell: curl -L "https://github.com/kubernetes-sigs/cri-tools/releases/download/{{CRICTL_VERSION}}/crictl-{{CRICTL_VERSION}}-linux-amd64.tar.gz" | tar -C /usr/local/bin -xz
      args:
        warn: no
    - systemd:
        name: containerd
        daemon_reload: yes
        state: restarted
        enabled: yes

# - hosts: localhost
#   gather_facts: no
#   tasks:
#     - archive:
#         path: /go/src/github.com/containerd/containerd/cmd/containerd/containerd
#         format: zip
# - hosts: all
#   become: yes
#   gather_facts: no
#   tasks:
#     - unarchive:
#         src: /go/src/github.com/containerd/containerd/cmd/containerd/containerd.zip
#         dest: /usr/bin
#     - systemd:
#         name: containerd
#         daemon_reload: yes
#         state: restarted
#         enabled: yes
