- hosts: all
  become: yes
  gather_facts: no
  tasks:
    - name: /etc/containerd
      file:
        path: /etc/containerd/
        state: directory
        owner: ubuntu
        group: ubuntu
    - name: /etc/containerd/config.toml
      shell:
        cmd: |
          cat > /etc/containerd/config.toml <<EOF
          #[debug]
          #  level = "trace"
          EOF
    - name: /etc/systemd/system/containerd.service.d
      file:
        path: /etc/systemd/system/containerd.service.d
        state: directory
    - name: /etc/systemd/system/containerd.service.d/override.conf
      shell:
        cmd: |
          cat > /etc/systemd/system/containerd.service.d/override.conf <<EOF
          [Service]
          #Environment="GODEBUG=http2debug=1"
          EOF
    - name: containerd
      apt:
        pkg: containerd
    # - copy:
    #     src: /go/src/github.com/containerd/containerd/cmd/containerd/containerd
    #     dest: /usr/bin/containerd
    - name: containerd
      systemd:
        name: containerd
        daemon_reload: yes
        state: restarted
        enabled: yes
    - name: crictl
      shell:
        cmd: |
          CRICTL_VERSION="v1.16.0"
          curl -L "https://github.com/kubernetes-sigs/cri-tools/releases/download/${CRICTL_VERSION}/crictl-${CRICTL_VERSION}-linux-amd64.tar.gz" | tar -C /usr/local/bin -xz
