- hosts: all
  gather_facts: no
  become: yes
  tasks:
    - name: kubeadm, kubelet, kubectl
      shell:
        executable: /bin/bash
        cmd: |
          RELEASE="$(curl -sSL https://dl.k8s.io/release/stable.txt)"
          cd /usr/local/bin
          curl -L --remote-name-all https://storage.googleapis.com/kubernetes-release/release/${RELEASE}/bin/linux/amd64/{kubeadm,kubelet,kubectl}
          chmod +x {kubeadm,kubelet,kubectl}

          curl -sSL "https://raw.githubusercontent.com/kubernetes/kubernetes/${RELEASE}/build/debs/kubelet.service" | sed "s:/usr/bin:/usr/local/bin:g" > /etc/systemd/system/kubelet.service
          mkdir -p /etc/systemd/system/kubelet.service.d
          curl -sSL "https://raw.githubusercontent.com/kubernetes/kubernetes/${RELEASE}/build/debs/10-kubeadm.conf" | sed "s:/usr/bin:/usr/local/bin:g" > /etc/systemd/system/kubelet.service.d/10-kubeadm.conf
    - copy:
        dest: /etc/default/kubelet
        content: |
          KUBELET_EXTRA_ARGS="-v=2 --cluster-dns=192.168.0.2"
    - systemd:
        name: kubelet
        daemon_reload: yes
        state: restarted
        enabled: yes

# - hosts: localhost
#   gather_facts: no
#   tasks:
#     - archive:
#         path: /go/src/github.com/kubernetes/kubernetes/cmd/kubelet/kubelet
#         format: zip
# - hosts: all
#   become: yes
#   gather_facts: no
#   tasks:
#     - unarchive:
#         src: /go/src/github.com/kubernetes/kubernetes/cmd/kubelet/kubelet.zip
#         dest: /usr/local/bin/
#     - systemd:
#         name: kubelet
#         daemon_reload: yes
#         state: restarted
#         enabled: yes
