- hosts: all
  gather_facts: no
  become: yes
  tasks:
    - shell:
        executable: /bin/bash
        cmd: |
          curl -s https://packages.cloud.google.com/apt/doc/apt-key.gpg | sudo apt-key add -
          cat <<EOF | sudo tee /etc/apt/sources.list.d/kubernetes.list
          deb https://apt.kubernetes.io/ kubernetes-xenial main
          EOF
    - name: kubeadm, kubelet, kubectl
      apt:
        update_cache: yes
        pkg:
          - kubelet
          - kubeadm
          - kubectl
    - copy:
        dest: /etc/default/kubelet
        content: |
          KUBELET_EXTRA_ARGS="-v=2 --fail-swap-on=false"
    - systemd:
        name: kubelet
        daemon_reload: yes
        state: restarted
        enabled: yes

# - hosts: localhost
#   gather_facts: no
#   tasks:
#     - archive:
#         path: /go/src/github.com/kubernetes/kubernetes/cmd/kubelet/kubelet
#         format: zip
# - hosts: all
#   become: yes
#   gather_facts: no
#   tasks:
#     - unarchive:
#         src: /go/src/github.com/kubernetes/kubernetes/cmd/kubelet/kubelet.zip
#         dest: /usr/local/bin/
#     - systemd:
#         name: kubelet
#         daemon_reload: yes
#         state: restarted
#         enabled: yes
