- hosts: master
  become: yes
  gather_facts: no
  tasks:
    - name: kubeadm init
      command: kubeadm init --node-name master
      register: output
    - debug: var=output
    - shell:
        cmd: |
          mkdir /home/ubuntu/.kube
          cp /etc/kubernetes/admin.conf /home/ubuntu/.kube/config
    - file:
        path: /home/ubuntu/.kube/config
        owner: ubuntu
        group: ubuntu
- hosts: master
  gather_facts: no
  tasks:
    - command: kubectl taint nodes --all node-role.kubernetes.io/master-
    - command: kubectl delete -n kube-system deploy/coredns      
