- hosts: master
  gather_facts: no
  tasks:
    - shell: kubectl get secrets -n kube-system --field-selector type=bootstrap.kubernetes.io/token --template='{{'{{'}}(index (index .items 0).data "token-id")}}' | base64 --decode
      register: token_id
    - shell: kubectl get secrets -n kube-system --field-selector type=bootstrap.kubernetes.io/token --template='{{'{{'}}(index (index .items 0).data "token-secret")}}' | base64 --decode
      register: token_secret
    - set_fact:
        token_id: "{{token_id.stdout_lines[0]}}"
        token_secret: "{{token_secret.stdout_lines[0]}}"
- hosts: worker
  gather_facts: no
  become: yes
  tasks:
    - command: kubeadm join {{ private_master_ip }}:6443 --token {{ hostvars['master']['token_id'] }}.{{ hostvars['master']['token_secret'] }} --node-name worker --discovery-token-unsafe-skip-ca-verification
      register: output
