- hosts: master
  gather_facts: no
  become: yes
  tasks:
    - name: kubeadm init
      command: kubeadm init --node-name master --ignore-preflight-errors=FileContent--proc-sys-net-ipv4-ip_forward,FileContent--proc-sys-net-bridge-bridge-nf-call-iptables
      register: output
    - debug: var=output.stdout_lines
    - shell:
        cmd: |
          mkdir /home/ubuntu/.kube
          cp /etc/kubernetes/admin.conf /home/ubuntu/.kube/config
    - file:
        path: /home/ubuntu/.kube
        owner: ubuntu
        group: ubuntu
        recurse: yes
- hosts: master
  gather_facts: no
  tasks:
    - command: kubectl taint nodes master node-role.kubernetes.io/master=:NoSchedule-
    - command: kubectl taint nodes master node-role.kubernetes.io/master=:PreferNoSchedule
    - command: kubectl delete -n kube-system deploy/coredns
