- hosts: master
  gather_facts: no
  become: yes
  tasks:
    - block:
        - name: kubeadm.conf
          copy:
            dest: kubeadm.conf
            content: |
              apiVersion: kubeadm.k8s.io/v1beta2
              kind: ClusterConfiguration
              apiServer:
                certSANs: ['{{ ansible_host }}']
                extraArgs:
                  enable-admission-plugins: PodPreset,NodeRestriction
                  runtime-config: settings.k8s.io/v1alpha1=true
        - name: kubeadm init
          command: kubeadm init --config kubeadm.conf --node-name master --ignore-preflight-errors=KubeletVersion
          register: output
        - debug: var=output.stdout_lines
        - name: .kube
          shell:
            cmd: |
              mkdir /home/ubuntu/.kube
              cp /etc/kubernetes/admin.conf /home/ubuntu/.kube/config
        - name: chown .kube
          file:
            path: /home/ubuntu/.kube
            owner: ubuntu
            group: ubuntu
            recurse: yes
      rescue:
        - debug: var=output.stderr_lines
        - fail:
            msg: "kubeadm init failed"
- hosts: master
  gather_facts: no
  tasks:
    - name: master is registry
      command: kubectl label node master node-role.kubernetes.io/registry=
    - name: master is schedulable
      command: kubectl taint node master node-role.kubernetes.io/master=:NoSchedule-
    - name: coredns replicas=1
      command: kubectl scale --replicas=1 deploy/coredns -n kube-system
    - name: log kube-proxy
      command: kubectl patch daemonset kube-proxy --type=json -p='[{"op":"add","path":"/spec/template/spec/containers/0/command/-","value":"-v=5"}]' -n kube-system
