- hosts: master
  gather_facts: no
  become: yes
  tasks:
    - block:
        - name: kubeadm init
          command: kubeadm init --node-name master --apiserver-cert-extra-sans '{{ public_master_ip }}' --ignore-preflight-errors=KubeletVersion
          register: output
        - debug: var=output.stdout_lines
        - shell:
            cmd: |
              mkdir /home/ubuntu/.kube
              cp /etc/kubernetes/admin.conf /home/ubuntu/.kube/config
        - file:
            path: /home/ubuntu/.kube
            owner: ubuntu
            group: ubuntu
            recurse: yes
      rescue:
        - debug: var=output.stderr_lines
        - fail:
            msg: "kubeadm init failed"
- hosts: master
  gather_facts: no
  tasks:
    - command: kubectl label node master node-role.kubernetes.io/registry=
    - command: kubectl taint node master node-role.kubernetes.io/master=:NoSchedule-
    - command: kubectl scale --replicas=1 deploy/coredns -n kube-system
    - command: kubectl patch daemonset kube-proxy --type=json -p='[{"op":"add","path":"/spec/template/spec/containers/0/command/-","value":"-v=5"}]' -n kube-system
