- hosts: master
  become: yes
  tasks:
    - file:
        path: /etc/cni/net.d
        state: directory
        owner: ubuntu
        group: ubuntu
    - name: loopback
      become: no
      shell:
        warn: no
        cmd: |
          cat > /etc/cni/net.d/99-loopback.conf <<EOF
          {
            "cniVersion": "0.2.0",
            "name": "lo",
            "type": "loopback"
          }
          EOF
