- hosts: all
  become: yes
  gather_facts: no
  tasks:
    - file:
        path: /etc/cni/net.d
        state: directory
        owner: ubuntu
        group: ubuntu
    - name: setup cluster network
      become: no
      shell:
        cmd: |
          cat > /etc/cni/net.d/10-mynet.conflist <<EOF
          {
            "cniVersion": "0.3.1",
            "name": "mynet",
            "plugins": [
              {
                "type": "ptp",
                "ipam": {
                  "type": "host-local",
                  "subnet": "172.16.30.0/24",
                  "routes": [
                    { "dst": "0.0.0.0/0" }
                  ]
                }
              },
              {
                "type": "portmap",
                "capabilities": { "portMappings": true }
              }
            ]
          }
          EOF
