- hosts: master
  become: yes
  tasks:
  - name: install CNI plugins
    shell:
      cmd: |
        CNI_VERSION="v0.8.2"
        mkdir -p /opt/cni/bin
        curl -L "https://github.com/containernetworking/plugins/releases/download/${CNI_VERSION}/cni-plugins-linux-amd64-${CNI_VERSION}.tgz" | tar -C /opt/cni/bin -xz
  - name: install crictl
    shell:
      cmd: |
        CRICTL_VERSION="v1.16.0"
        mkdir -p /opt/bin
        curl -L "https://github.com/kubernetes-sigs/cri-tools/releases/download/${CRICTL_VERSION}/crictl-${CRICTL_VERSION}-linux-amd64.tar.gz" | tar -C /opt/bin -xz
  - name: install kubeadm, kubelet, kubectl
    shell:
      executable: /bin/bash
      cmd: |
        RELEASE="$(curl -sSL https://dl.k8s.io/release/stable.txt)"
        mkdir -p /opt/bin
        cd /opt/bin
        curl -L --remote-name-all https://storage.googleapis.com/kubernetes-release/release/${RELEASE}/bin/linux/amd64/{kubeadm,kubelet,kubectl}
        chmod +x {kubeadm,kubelet,kubectl}

        curl -sSL "https://raw.githubusercontent.com/kubernetes/kubernetes/${RELEASE}/build/debs/kubelet.service" | sed "s:/usr/bin:/opt/bin:g" > /etc/systemd/system/kubelet.service
        mkdir -p /etc/systemd/system/kubelet.service.d
        curl -sSL "https://raw.githubusercontent.com/kubernetes/kubernetes/${RELEASE}/build/debs/10-kubeadm.conf" | sed "s:/usr/bin:/opt/bin:g" > /etc/systemd/system/kubelet.service.d/10-kubeadm.conf
  - name: start kubelet
    systemd:
      name: kubelet
      enabled: yes
  - name: chown
    file:
      path: /opt/bin/kubeadm
      owner: ubuntu
      group: ubuntu
  - name: chown
    file:
      path: /opt/bin/kubectl
      owner: ubuntu
      group: ubuntu
  